---
- name: Daploying Database
  hosts: database
  become: yes
  roles:
    - database

- name: Deploying Backend
  hosts: backend
  become: yes
  roles:
    - backend

- name: Dploying Frontend
  hosts: frontend
  become: yes
  roles:
    - frontend
