---

- name: Install PostgreSQL
  hosts: database
  become: yes
  vars:
    db_name: "my_psql_db"
    user_name: "userabc"
    user_password: "password123"
    backup_dir: /var/backups/postgresql
    backup_script_path: /usr/local/bin/backup.sh
    backup_time: "0 2 * * *"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - acl
          - python3-pip
          - python3-psycopg2
        state: present
        update_cache: yes

    - name: Add pgdg repo to sources.list.d
      lineinfile:
        path: /etc/apt/sources.list.d/pgdg.list
        line: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        create: yes

    - name: Download PostgreSQL key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Enable service
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create a user
      become_user: postgres
      postgresql_user:
        name: "{{ user_name }}"
        password: "{{ user_password }}"
        db: "{{ db_name }}"
        priv: "ALL"
        state: present

    - name: Deploy PostgreSQL configuration file
      template:
        src: templates/pg_hba.conf.j2
        dest: /etc/postgresql/16/main/pg_hba.conf
      notify:
        - Restart PostgreSQL

    - name: Ensure backup directory exists
      file:
        path: "{{ backup_dir }}"
        state: directory
        owner: postgres
        group: postgres
        mode: '0755'

    - name: Deploy PostgreSQL backup script
      copy:
        src: backup.sh
        dest: "{{ backup_script_path }}"
        owner: root
        group: root
        mode: '0755'

    - name: Create cron job for PostgreSQL backup
      cron:
        name: "PostgreSQL backup"
        user: postgres
        minute: "{{ backup_time.split()[0] }}"
        hour: "{{ backup_time.split()[1] }}"
        job: "{{ backup_script_path }}"

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted

