---
- name: Daploying Database
  hosts: all
  become: yes
  roles:
    - database

- name: Deploying Backend
  hosts: all
  become: yes
  roles:
    - backend

- name: Dploying Frontend
  hosts: all
  become: yes
  roles:
    - frontend