---
- name: Configure a service
  hosts: all
  become: yes
  tasks:
    - name: Ensure nginx service is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
