---
- name: Manage files on managed nodes
  hosts: all
  become: yes
  tasks:
    - name: Create a file with specific content
      copy:
        dest: /tmp/example_file.txt
        content: |
          This is an example file created by Ansible.
        owner: root
        group: root
        mode: '0644'
    
    - name: Modify the file content
      lineinfile:
        path: /tmp/example_file.txt
        line: 'This line was added by Ansible.'
        create: yes

    - name: Delete an example file
      file:
        path: /tmp/example_file_to_delete.txt
        state: absent
